//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ALQUILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_ALQUILER()
        {
            this.Alquiler = new HashSet<Alquiler>();
        }
    
        public int ID_DETALLE_ALQUILER { get; set; }
        public int ID_MONTO_PAGO { get; set; }
        public Nullable<int> ID_LIBRO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alquiler> Alquiler { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual LIBRO LIBRO { get; set; }
        public virtual MONTO_PAGO MONTO_PAGO { get; set; }
    }
}
