//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBRO()
        {
            this.DETALLE_ALQUILER = new HashSet<DETALLE_ALQUILER>();
        }
    
        public int ID_LIBRO { get; set; }
        public Nullable<int> ANO_LIBRO { get; set; }
        public string ESTADO_LIBRO { get; set; }
        public string TITULO_LIBRO { get; set; }
        public string CONTENIDO { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> ID_EDITORIAL_LIBRO { get; set; }
        public Nullable<int> ID_AUTOR_LIBRO { get; set; }
    
        public virtual AUTOR AUTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ALQUILER> DETALLE_ALQUILER { get; set; }
        public virtual EDITORIAL EDITORIAL { get; set; }
    }
}
