//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTO_PAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONTO_PAGO()
        {
            this.DETALLE_ALQUILER = new HashSet<DETALLE_ALQUILER>();
        }
    
        public int ID_MONTO_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_MONTO_PAGO { get; set; }
        public Nullable<decimal> MONTO_PAGO1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ALQUILER> DETALLE_ALQUILER { get; set; }
    }
}
